### ISSUE TITLE
recall is called with same args

### ISSUE THREAD

**Issue by Kepro** [ArnoSaine/postinumero#2]
```typescript

const [useData, recall] = create(
  async (name: string, date?: string) => {
     console.log(name, date);
   }
};

const Component = () => {
   const data = useData('test');

   useEffect(() => {
      recall('anything', something); // still called with test
   }, [something]);
}
```

**Comment by ArnoSaine** [comment]
Hi!

`recall` is probably not needed here if you want to rerun the function with different args. Can you you organize the code so that `useData` gets the new args, maybe from props, state or context?

`recall` is for triggering a rerun of the function some time later with the same args. `recall` above should not trigger a rerun as the args are not the same. Is there anything that may trigger a remount of the `Component`?

**Comment by Kepro** [comment]
well `recall` is accepting args (from typing) so I was expecting that it's kind of a nice way to retrigger the original hook with new args,  but yeah option with moving hooks and reacting on state/props change will solve it of course

**Comment by Kepro** [comment]
byt okay... rereading docs

```
If there are components currently mounted using any of the hooks and the *same* arguments (fn, config, args), fn(...args) gets called. When fn resolves, components will rerender with the new value.
```
